name: Build Termux Wheel to Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Build frontend
        run: |
          npm install
          npm run build
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      - name: Install dependencies and Android target
        run: |
          pip install maturin
          rustup target add aarch64-linux-android
      - name: Set up CPython interpreter for cross-compilation
        run: |
          BASE_URL="https://packages.termux.dev/apt/termux-main/pool/main/p/python"
          FNAME=$(curl -s "$BASE_URL/" | grep -oP '(?<=href=")python_[^"]+_aarch64\.deb' | head -n 1)
          wget -nv "$BASE_URL/$FNAME"
          mkdir python
          dpkg-deb -x $FNAME python
          cp -a python/data/data/com.termux/files/usr/lib/libpython* $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/24
          sed -i 's/"abi3-py38",\? *//g' crates/stream-gears/Cargo.toml
          sed -i '/dependencies = \[/a\    "quickjs >= 1.19.4",' pyproject.toml
          sed -i 's/aiohttp\[speedups\] >= 3\.9\.5/aiohttp[speedups] <= 3.9.5/' pyproject.toml
      - name: Build wheel for aarch64 (Termux)
        run: |
          export NDK_BIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          export CC_aarch64_linux_android=$NDK_BIN/aarch64-linux-android24-clang
          export AR_aarch64_linux_android=$NDK_BIN/llvm-ar
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$NDK_BIN/aarch64-linux-android24-clang
          export PYO3_CROSS_LIB_DIR=python/data/data/com.termux/files/usr/lib/
          maturin build \
            --release \
            --strip \
            --manylinux off \
            --target aarch64-linux-android \
            --out dist
      - name: Upload wheel to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
